# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""Raven model configuration (package-owned Pydantic schema + adapter).

Mirrors the plugin pattern used by dRoute/jHBV: the package owns its
:class:`RavenConfig` schema and registers it via ``model_manifest(config_schema=...)``.
:class:`RavenConfigAdapter` (an ``AutoGeneratedConfigAdapter``) derives defaults and
flat->nested transformers from the Field declarations, so every ``RAVEN_*`` key is
recognized by SYMFLUENCE's config validation.
"""
from __future__ import annotations

from typing import Any, Dict, Literal

from pydantic import BaseModel, Field
from symfluence.core.config.models.base import FROZEN_CONFIG
from symfluence.models.base import AutoGeneratedConfigAdapter

# Raven emulator structures supported via RavenPy (all eight hydrologic emulators).
RAVEN_MODEL_TEMPLATES = (
    "GR4JCN", "HBVEC", "HMETS", "MOHYSE",
    "BLENDED", "CANADIANSHIELD", "HYPR", "SACSMA",
)


class RavenConfig(BaseModel):
    """Configuration for the Raven hydrological modelling framework.

    Raven (U. Waterloo) is a flexible, single-binary engine that emulates many
    model structures. This plugin drives it through RavenPy, fed from SYMFLUENCE's
    model-ready datastore.
    """
    model_config = FROZEN_CONFIG

    # Structure / spatial mode
    model_template: Literal[
        "GR4JCN", "HBVEC", "HMETS", "MOHYSE",
        "BLENDED", "CANADIANSHIELD", "HYPR", "SACSMA",
    ] = Field(
        default="GR4JCN",
        alias="RAVEN_MODEL_TEMPLATE",
        description="Raven emulator structure to run/calibrate",
    )
    spatial_mode: Literal["lumped", "distributed"] = Field(
        default="lumped",
        alias="RAVEN_SPATIAL_MODE",
        description="lumped (single HRU/subbasin) or distributed (HRUs + routing topology)",
    )
    routing_method: str = Field(
        default="ROUTE_DIFFUSIVE_WAVE",
        alias="RAVEN_ROUTING_METHOD",
        description="Raven in-channel routing method for distributed mode (e.g. "
                    "ROUTE_DIFFUSIVE_WAVE, ROUTE_HYDROLOGIC, ROUTE_NONE)",
    )

    # Binary / paths
    install_path: str = Field(default="default", alias="RAVEN_INSTALL_PATH")
    exe: str = Field(default="raven", alias="RAVEN_EXE")
    settings_path: str = Field(default="default", alias="SETTINGS_RAVEN_PATH")
    run_name: str = Field(default="raven_run", alias="RAVEN_RUN_NAME")

    # Calibration
    params_to_calibrate: str = Field(
        default="default",
        alias="RAVEN_PARAMS_TO_CALIBRATE",
        description="Comma-separated parameter names; 'default' = full set for the model_template",
    )
    calibrate: bool = Field(default=False, alias="CALIBRATE_RAVEN")
    timeout: int = Field(default=3600, alias="RAVEN_TIMEOUT", ge=60, le=86400)

    # Output
    experiment_output: str = Field(default="default", alias="EXPERIMENT_OUTPUT_RAVEN")
    experiment_log: str = Field(default="default", alias="EXPERIMENT_LOG_RAVEN")


class RavenConfigAdapter(AutoGeneratedConfigAdapter):
    """Config adapter: defaults + transformers auto-derived from :class:`RavenConfig`."""

    def __init__(self, model_name: str = "RAVEN"):
        super().__init__(model_name)

    def get_config_schema(self):
        return RavenConfig

    def validate(self, config: Dict[str, Any]) -> None:
        template = config.get("model_template", "GR4JCN")
        if template not in RAVEN_MODEL_TEMPLATES:
            raise ValueError(
                f"Invalid RAVEN_MODEL_TEMPLATE '{template}'. "
                f"Must be one of: {list(RAVEN_MODEL_TEMPLATES)}"
            )
        spatial_mode = config.get("spatial_mode", "lumped")
        if spatial_mode not in ("lumped", "distributed"):
            raise ValueError(
                f"Invalid RAVEN_SPATIAL_MODE '{spatial_mode}'. Must be 'lumped' or 'distributed'."
            )
